services:
  gateway:
    - id: gw-1
      tcp_listen: 0.0.0.0:8999
      ws_listen: 0.0.0.0:9000
      public_addr: 127.0.0.1:8999
    - id: gw-2
      tcp_listen: 0.0.0.0:9000
      ws_listen: 0.0.0.0:9001
      public_addr: 127.0.0.1:9000

  chatsvr:
    - id: cs-1
      listen: 0.0.0.0:8001
      public_addr: 127.0.0.1:8001

gateway:
  jwt_secret: "change-me-in-production"
  routes:
    chatsvr:
      forward: [5]          # MsgIdChat
      route_key: playerId