// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: cardwar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_cardwar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_cardwar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_cardwar_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type LoginRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	mi := &file_cardwar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cardwar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_cardwar_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRsp) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *LoginRsp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChatReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Content        string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TargetPlayerId int64                  `protobuf:"varint,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"` // 0 = global, non-zero = private target
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	mi := &file_cardwar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_cardwar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_cardwar_proto_rawDescGZIP(), []int{2}
}

func (x *ChatReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatReq) GetTargetPlayerId() int64 {
	if x != nil {
		return x.TargetPlayerId
	}
	return 0
}

type ChatResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderPlayerId int64                  `protobuf:"varint,1,opt,name=sender_player_id,json=senderPlayerId,proto3" json:"sender_player_id,omitempty"`
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TargetPlayerId int64                  `protobuf:"varint,4,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"` // 0 = global, non-zero = private recipient
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatResp) Reset() {
	*x = ChatResp{}
	mi := &file_cardwar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResp) ProtoMessage() {}

func (x *ChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_cardwar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResp.ProtoReflect.Descriptor instead.
func (*ChatResp) Descriptor() ([]byte, []int) {
	return file_cardwar_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResp) GetSenderPlayerId() int64 {
	if x != nil {
		return x.SenderPlayerId
	}
	return 0
}

func (x *ChatResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChatResp) GetTargetPlayerId() int64 {
	if x != nil {
		return x.TargetPlayerId
	}
	return 0
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ConnTags      map[string]string      `protobuf:"bytes,3,rep,name=conn_tags,json=connTags,proto3" json:"conn_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_cardwar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_cardwar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_cardwar_proto_rawDescGZIP(), []int{4}
}

func (x *Envelope) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *Envelope) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Envelope) GetConnTags() map[string]string {
	if x != nil {
		return x.ConnTags
	}
	return nil
}

var File_cardwar_proto protoreflect.FileDescriptor

const file_cardwar_proto_rawDesc = "" +
	"\n" +
	"\rcardwar.proto\x12\x02pb\"'\n" +
	"\bLoginReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"[\n" +
	"\bLoginRsp\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"M\n" +
	"\aChatReq\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\x03R\x0etargetPlayerId\"\x96\x01\n" +
	"\bChatResp\x12(\n" +
	"\x10sender_player_id\x18\x01 \x01(\x03R\x0esenderPlayerId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12(\n" +
	"\x10target_player_id\x18\x04 \x01(\x03R\x0etargetPlayerId\"\xad\x01\n" +
	"\bEnvelope\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\x04R\x06connId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x127\n" +
	"\tconn_tags\x18\x03 \x03(\v2\x1a.pb.Envelope.ConnTagsEntryR\bconnTags\x1a;\n" +
	"\rConnTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x15Z\x13cardwar/protocol/pbb\x06proto3"

var (
	file_cardwar_proto_rawDescOnce sync.Once
	file_cardwar_proto_rawDescData []byte
)

func file_cardwar_proto_rawDescGZIP() []byte {
	file_cardwar_proto_rawDescOnce.Do(func() {
		file_cardwar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cardwar_proto_rawDesc), len(file_cardwar_proto_rawDesc)))
	})
	return file_cardwar_proto_rawDescData
}

var file_cardwar_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cardwar_proto_goTypes = []any{
	(*LoginReq)(nil), // 0: pb.LoginReq
	(*LoginRsp)(nil), // 1: pb.LoginRsp
	(*ChatReq)(nil),  // 2: pb.ChatReq
	(*ChatResp)(nil), // 3: pb.ChatResp
	(*Envelope)(nil), // 4: pb.Envelope
	nil,              // 5: pb.Envelope.ConnTagsEntry
}
var file_cardwar_proto_depIdxs = []int32{
	5, // 0: pb.Envelope.conn_tags:type_name -> pb.Envelope.ConnTagsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cardwar_proto_init() }
func file_cardwar_proto_init() {
	if File_cardwar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cardwar_proto_rawDesc), len(file_cardwar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cardwar_proto_goTypes,
		DependencyIndexes: file_cardwar_proto_depIdxs,
		MessageInfos:      file_cardwar_proto_msgTypes,
	}.Build()
	File_cardwar_proto = out.File
	file_cardwar_proto_goTypes = nil
	file_cardwar_proto_depIdxs = nil
}
