// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: match.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchEnterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchType     string                 `protobuf:"bytes,1,opt,name=match_type,json=matchType,proto3" json:"match_type,omitempty"` // "1v1" | "2v2" | "3v3" | "5v5"
	Elo           int64                  `protobuf:"varint,2,opt,name=elo,proto3" json:"elo,omitempty"`                             // optional, for skill-based matching
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEnterReq) Reset() {
	*x = MatchEnterReq{}
	mi := &file_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEnterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEnterReq) ProtoMessage() {}

func (x *MatchEnterReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEnterReq.ProtoReflect.Descriptor instead.
func (*MatchEnterReq) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{0}
}

func (x *MatchEnterReq) GetMatchType() string {
	if x != nil {
		return x.MatchType
	}
	return ""
}

func (x *MatchEnterReq) GetElo() int64 {
	if x != nil {
		return x.Elo
	}
	return 0
}

type MatchEnterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                         // "waiting"
	QueueSize     int64                  `protobuf:"varint,2,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"` // current players in this queue
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEnterResp) Reset() {
	*x = MatchEnterResp{}
	mi := &file_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEnterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEnterResp) ProtoMessage() {}

func (x *MatchEnterResp) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEnterResp.ProtoReflect.Descriptor instead.
func (*MatchEnterResp) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{1}
}

func (x *MatchEnterResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatchEnterResp) GetQueueSize() int64 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

type MatchResultPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Players       []int64                `protobuf:"varint,3,rep,packed,name=players,proto3" json:"players,omitempty"`
	MatchType     string                 `protobuf:"bytes,4,opt,name=match_type,json=matchType,proto3" json:"match_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResultPush) Reset() {
	*x = MatchResultPush{}
	mi := &file_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResultPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResultPush) ProtoMessage() {}

func (x *MatchResultPush) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResultPush.ProtoReflect.Descriptor instead.
func (*MatchResultPush) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{2}
}

func (x *MatchResultPush) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchResultPush) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MatchResultPush) GetPlayers() []int64 {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MatchResultPush) GetMatchType() string {
	if x != nil {
		return x.MatchType
	}
	return ""
}

type MatchAllocateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"` // desired match ID (e.g., "room-lobby-1")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchAllocateReq) Reset() {
	*x = MatchAllocateReq{}
	mi := &file_match_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchAllocateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchAllocateReq) ProtoMessage() {}

func (x *MatchAllocateReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchAllocateReq.ProtoReflect.Descriptor instead.
func (*MatchAllocateReq) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{3}
}

func (x *MatchAllocateReq) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type MatchAllocateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // assigned roomsvr instance
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                       // empty = success, "already exists" | "no roomsvr available"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchAllocateResp) Reset() {
	*x = MatchAllocateResp{}
	mi := &file_match_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchAllocateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchAllocateResp) ProtoMessage() {}

func (x *MatchAllocateResp) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchAllocateResp.ProtoReflect.Descriptor instead.
func (*MatchAllocateResp) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{4}
}

func (x *MatchAllocateResp) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchAllocateResp) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MatchAllocateResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MatchQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"` // which match to look up
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchQueryReq) Reset() {
	*x = MatchQueryReq{}
	mi := &file_match_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchQueryReq) ProtoMessage() {}

func (x *MatchQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchQueryReq.ProtoReflect.Descriptor instead.
func (*MatchQueryReq) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{5}
}

func (x *MatchQueryReq) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type MatchQueryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchQueryResp) Reset() {
	*x = MatchQueryResp{}
	mi := &file_match_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchQueryResp) ProtoMessage() {}

func (x *MatchQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchQueryResp.ProtoReflect.Descriptor instead.
func (*MatchQueryResp) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{6}
}

func (x *MatchQueryResp) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchQueryResp) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MatchQueryResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_match_proto protoreflect.FileDescriptor

const file_match_proto_rawDesc = "" +
	"\n" +
	"\vmatch.proto\x12\x02pb\"@\n" +
	"\rMatchEnterReq\x12\x1d\n" +
	"\n" +
	"match_type\x18\x01 \x01(\tR\tmatchType\x12\x10\n" +
	"\x03elo\x18\x02 \x01(\x03R\x03elo\"G\n" +
	"\x0eMatchEnterResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"queue_size\x18\x02 \x01(\x03R\tqueueSize\"\x82\x01\n" +
	"\x0fMatchResultPush\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x18\n" +
	"\aplayers\x18\x03 \x03(\x03R\aplayers\x12\x1d\n" +
	"\n" +
	"match_type\x18\x04 \x01(\tR\tmatchType\"-\n" +
	"\x10MatchAllocateReq\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"a\n" +
	"\x11MatchAllocateResp\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"*\n" +
	"\rMatchQueryReq\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"^\n" +
	"\x0eMatchQueryResp\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05foundB\x15Z\x13cardwar/protocol/pbb\x06proto3"

var (
	file_match_proto_rawDescOnce sync.Once
	file_match_proto_rawDescData []byte
)

func file_match_proto_rawDescGZIP() []byte {
	file_match_proto_rawDescOnce.Do(func() {
		file_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_match_proto_rawDesc), len(file_match_proto_rawDesc)))
	})
	return file_match_proto_rawDescData
}

var file_match_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_match_proto_goTypes = []any{
	(*MatchEnterReq)(nil),     // 0: pb.MatchEnterReq
	(*MatchEnterResp)(nil),    // 1: pb.MatchEnterResp
	(*MatchResultPush)(nil),   // 2: pb.MatchResultPush
	(*MatchAllocateReq)(nil),  // 3: pb.MatchAllocateReq
	(*MatchAllocateResp)(nil), // 4: pb.MatchAllocateResp
	(*MatchQueryReq)(nil),     // 5: pb.MatchQueryReq
	(*MatchQueryResp)(nil),    // 6: pb.MatchQueryResp
}
var file_match_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_match_proto_init() }
func file_match_proto_init() {
	if File_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_match_proto_rawDesc), len(file_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_match_proto_goTypes,
		DependencyIndexes: file_match_proto_depIdxs,
		MessageInfos:      file_match_proto_msgTypes,
	}.Build()
	File_match_proto = out.File
	file_match_proto_goTypes = nil
	file_match_proto_depIdxs = nil
}
