// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: msgid.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message IDs for Zinx routing. All client-server messages are routed by these.
type MsgID int32

const (
	MsgID_MSG_ID_UNSPECIFIED MsgID = 0
	MsgID_PING               MsgID = 1
	MsgID_PONG               MsgID = 2
	MsgID_CHAT_REQ           MsgID = 5
	MsgID_CHAT_RESP          MsgID = 6
	// 服务间身份交换
	MsgID_SERVICE_IDENTITY MsgID = 1001
	// ===== match pool
	MsgID_MATCH_ENTER_REQ   MsgID = 11
	MsgID_MATCH_ENTER_RESP  MsgID = 12
	MsgID_MATCH_RESULT_PUSH MsgID = 13
	// ===== match directory
	MsgID_MATCH_ALLOCATE_REQ  MsgID = 18
	MsgID_MATCH_ALLOCATE_RESP MsgID = 19
	MsgID_MATCH_QUERY_REQ     MsgID = 20
	MsgID_MATCH_QUERY_RESP    MsgID = 21
	// ===== room
	MsgID_ROOM_JOIN_REQ       MsgID = 14
	MsgID_ROOM_JOIN_RESP      MsgID = 15
	MsgID_ROOM_LEAVE_REQ      MsgID = 16
	MsgID_ROOM_LEAVE_RESP     MsgID = 17
	MsgID_ROOM_DESTROYED_PUSH MsgID = 22 // RoomSvr → MatchSvr (internal)
	MsgID_ROOM_EVENT_PUSH     MsgID = 23 // RoomSvr → Client (joined/left broadcast)
	// ===== session (disconnect / reconnect)
	MsgID_SESSION_SAVE              MsgID = 1002 // Gateway → SessionSvr: sync conn_tags
	MsgID_SESSION_GET               MsgID = 1003 // Gateway → SessionSvr: query session
	MsgID_SESSION_DISCONNECT        MsgID = 1004 // Gateway → SessionSvr: mark disconnected
	MsgID_SESSION_RECONNECT         MsgID = 1005 // Gateway → SessionSvr: mark reconnected
	MsgID_SESSION_FORCE_LEAVE       MsgID = 1006 // SessionSvr → RoomSvr: TTL expired, force leave room
	MsgID_SESSION_FORCE_LEAVE_QUEUE MsgID = 1007 // SessionSvr → MatchSvr: TTL expired, force leave queue
	MsgID_SESSION_RECONNECTED       MsgID = 1008 // Gateway → RoomSvr: player reconnected, update conn
)

// Enum value maps for MsgID.
var (
	MsgID_name = map[int32]string{
		0:    "MSG_ID_UNSPECIFIED",
		1:    "PING",
		2:    "PONG",
		5:    "CHAT_REQ",
		6:    "CHAT_RESP",
		1001: "SERVICE_IDENTITY",
		11:   "MATCH_ENTER_REQ",
		12:   "MATCH_ENTER_RESP",
		13:   "MATCH_RESULT_PUSH",
		18:   "MATCH_ALLOCATE_REQ",
		19:   "MATCH_ALLOCATE_RESP",
		20:   "MATCH_QUERY_REQ",
		21:   "MATCH_QUERY_RESP",
		14:   "ROOM_JOIN_REQ",
		15:   "ROOM_JOIN_RESP",
		16:   "ROOM_LEAVE_REQ",
		17:   "ROOM_LEAVE_RESP",
		22:   "ROOM_DESTROYED_PUSH",
		23:   "ROOM_EVENT_PUSH",
		1002: "SESSION_SAVE",
		1003: "SESSION_GET",
		1004: "SESSION_DISCONNECT",
		1005: "SESSION_RECONNECT",
		1006: "SESSION_FORCE_LEAVE",
		1007: "SESSION_FORCE_LEAVE_QUEUE",
		1008: "SESSION_RECONNECTED",
	}
	MsgID_value = map[string]int32{
		"MSG_ID_UNSPECIFIED":        0,
		"PING":                      1,
		"PONG":                      2,
		"CHAT_REQ":                  5,
		"CHAT_RESP":                 6,
		"SERVICE_IDENTITY":          1001,
		"MATCH_ENTER_REQ":           11,
		"MATCH_ENTER_RESP":          12,
		"MATCH_RESULT_PUSH":         13,
		"MATCH_ALLOCATE_REQ":        18,
		"MATCH_ALLOCATE_RESP":       19,
		"MATCH_QUERY_REQ":           20,
		"MATCH_QUERY_RESP":          21,
		"ROOM_JOIN_REQ":             14,
		"ROOM_JOIN_RESP":            15,
		"ROOM_LEAVE_REQ":            16,
		"ROOM_LEAVE_RESP":           17,
		"ROOM_DESTROYED_PUSH":       22,
		"ROOM_EVENT_PUSH":           23,
		"SESSION_SAVE":              1002,
		"SESSION_GET":               1003,
		"SESSION_DISCONNECT":        1004,
		"SESSION_RECONNECT":         1005,
		"SESSION_FORCE_LEAVE":       1006,
		"SESSION_FORCE_LEAVE_QUEUE": 1007,
		"SESSION_RECONNECTED":       1008,
	}
)

func (x MsgID) Enum() *MsgID {
	p := new(MsgID)
	*p = x
	return p
}

func (x MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_msgid_proto_enumTypes[0].Descriptor()
}

func (MsgID) Type() protoreflect.EnumType {
	return &file_msgid_proto_enumTypes[0]
}

func (x MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgID.Descriptor instead.
func (MsgID) EnumDescriptor() ([]byte, []int) {
	return file_msgid_proto_rawDescGZIP(), []int{0}
}

var File_msgid_proto protoreflect.FileDescriptor

const file_msgid_proto_rawDesc = "" +
	"\n" +
	"\vmsgid.proto\x12\x02pb*\xad\x04\n" +
	"\x05MsgID\x12\x16\n" +
	"\x12MSG_ID_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04PING\x10\x01\x12\b\n" +
	"\x04PONG\x10\x02\x12\f\n" +
	"\bCHAT_REQ\x10\x05\x12\r\n" +
	"\tCHAT_RESP\x10\x06\x12\x15\n" +
	"\x10SERVICE_IDENTITY\x10\xe9\a\x12\x13\n" +
	"\x0fMATCH_ENTER_REQ\x10\v\x12\x14\n" +
	"\x10MATCH_ENTER_RESP\x10\f\x12\x15\n" +
	"\x11MATCH_RESULT_PUSH\x10\r\x12\x16\n" +
	"\x12MATCH_ALLOCATE_REQ\x10\x12\x12\x17\n" +
	"\x13MATCH_ALLOCATE_RESP\x10\x13\x12\x13\n" +
	"\x0fMATCH_QUERY_REQ\x10\x14\x12\x14\n" +
	"\x10MATCH_QUERY_RESP\x10\x15\x12\x11\n" +
	"\rROOM_JOIN_REQ\x10\x0e\x12\x12\n" +
	"\x0eROOM_JOIN_RESP\x10\x0f\x12\x12\n" +
	"\x0eROOM_LEAVE_REQ\x10\x10\x12\x13\n" +
	"\x0fROOM_LEAVE_RESP\x10\x11\x12\x17\n" +
	"\x13ROOM_DESTROYED_PUSH\x10\x16\x12\x13\n" +
	"\x0fROOM_EVENT_PUSH\x10\x17\x12\x11\n" +
	"\fSESSION_SAVE\x10\xea\a\x12\x10\n" +
	"\vSESSION_GET\x10\xeb\a\x12\x17\n" +
	"\x12SESSION_DISCONNECT\x10\xec\a\x12\x16\n" +
	"\x11SESSION_RECONNECT\x10\xed\a\x12\x18\n" +
	"\x13SESSION_FORCE_LEAVE\x10\xee\a\x12\x1e\n" +
	"\x19SESSION_FORCE_LEAVE_QUEUE\x10\xef\a\x12\x18\n" +
	"\x13SESSION_RECONNECTED\x10\xf0\aB\x15Z\x13cardwar/protocol/pbb\x06proto3"

var (
	file_msgid_proto_rawDescOnce sync.Once
	file_msgid_proto_rawDescData []byte
)

func file_msgid_proto_rawDescGZIP() []byte {
	file_msgid_proto_rawDescOnce.Do(func() {
		file_msgid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msgid_proto_rawDesc), len(file_msgid_proto_rawDesc)))
	})
	return file_msgid_proto_rawDescData
}

var file_msgid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msgid_proto_goTypes = []any{
	(MsgID)(0), // 0: pb.MsgID
}
var file_msgid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msgid_proto_init() }
func file_msgid_proto_init() {
	if File_msgid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msgid_proto_rawDesc), len(file_msgid_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgid_proto_goTypes,
		DependencyIndexes: file_msgid_proto_depIdxs,
		EnumInfos:         file_msgid_proto_enumTypes,
	}.Build()
	File_msgid_proto = out.File
	file_msgid_proto_goTypes = nil
	file_msgid_proto_depIdxs = nil
}
