// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: msgid.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message IDs for Zinx routing. All client-server messages are routed by these.
type MsgID int32

const (
	MsgID_MSG_ID_UNSPECIFIED MsgID = 0
	MsgID_PING               MsgID = 1
	MsgID_PONG               MsgID = 2
	MsgID_CHAT_REQ           MsgID = 5
	MsgID_CHAT_RESP          MsgID = 6
	// 注册信息
	MsgID_GATEWAY_REGISTER MsgID = 1000
)

// Enum value maps for MsgID.
var (
	MsgID_name = map[int32]string{
		0:    "MSG_ID_UNSPECIFIED",
		1:    "PING",
		2:    "PONG",
		5:    "CHAT_REQ",
		6:    "CHAT_RESP",
		1000: "GATEWAY_REGISTER",
	}
	MsgID_value = map[string]int32{
		"MSG_ID_UNSPECIFIED": 0,
		"PING":               1,
		"PONG":               2,
		"CHAT_REQ":           5,
		"CHAT_RESP":          6,
		"GATEWAY_REGISTER":   1000,
	}
)

func (x MsgID) Enum() *MsgID {
	p := new(MsgID)
	*p = x
	return p
}

func (x MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_msgid_proto_enumTypes[0].Descriptor()
}

func (MsgID) Type() protoreflect.EnumType {
	return &file_msgid_proto_enumTypes[0]
}

func (x MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgID.Descriptor instead.
func (MsgID) EnumDescriptor() ([]byte, []int) {
	return file_msgid_proto_rawDescGZIP(), []int{0}
}

var File_msgid_proto protoreflect.FileDescriptor

const file_msgid_proto_rawDesc = "" +
	"\n" +
	"\vmsgid.proto\x12\x02pb*g\n" +
	"\x05MsgID\x12\x16\n" +
	"\x12MSG_ID_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04PING\x10\x01\x12\b\n" +
	"\x04PONG\x10\x02\x12\f\n" +
	"\bCHAT_REQ\x10\x05\x12\r\n" +
	"\tCHAT_RESP\x10\x06\x12\x15\n" +
	"\x10GATEWAY_REGISTER\x10\xe8\aB\x15Z\x13cardwar/protocol/pbb\x06proto3"

var (
	file_msgid_proto_rawDescOnce sync.Once
	file_msgid_proto_rawDescData []byte
)

func file_msgid_proto_rawDescGZIP() []byte {
	file_msgid_proto_rawDescOnce.Do(func() {
		file_msgid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msgid_proto_rawDesc), len(file_msgid_proto_rawDesc)))
	})
	return file_msgid_proto_rawDescData
}

var file_msgid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msgid_proto_goTypes = []any{
	(MsgID)(0), // 0: pb.MsgID
}
var file_msgid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msgid_proto_init() }
func file_msgid_proto_init() {
	if File_msgid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msgid_proto_rawDesc), len(file_msgid_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgid_proto_goTypes,
		DependencyIndexes: file_msgid_proto_depIdxs,
		EnumInfos:         file_msgid_proto_enumTypes,
	}.Build()
	File_msgid_proto = out.File
	file_msgid_proto_goTypes = nil
	file_msgid_proto_depIdxs = nil
}
