// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: room.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomJoinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoinReq) Reset() {
	*x = RoomJoinReq{}
	mi := &file_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinReq) ProtoMessage() {}

func (x *RoomJoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinReq.ProtoReflect.Descriptor instead.
func (*RoomJoinReq) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

func (x *RoomJoinReq) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type RoomJoinResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MatchId       string                 `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoinResp) Reset() {
	*x = RoomJoinResp{}
	mi := &file_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinResp) ProtoMessage() {}

func (x *RoomJoinResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinResp.ProtoReflect.Descriptor instead.
func (*RoomJoinResp) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomJoinResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoomJoinResp) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *RoomJoinResp) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RoomJoinResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RoomLeaveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomLeaveReq) Reset() {
	*x = RoomLeaveReq{}
	mi := &file_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomLeaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLeaveReq) ProtoMessage() {}

func (x *RoomLeaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLeaveReq.ProtoReflect.Descriptor instead.
func (*RoomLeaveReq) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2}
}

func (x *RoomLeaveReq) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type RoomLeaveResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomLeaveResp) Reset() {
	*x = RoomLeaveResp{}
	mi := &file_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomLeaveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLeaveResp) ProtoMessage() {}

func (x *RoomLeaveResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLeaveResp.ProtoReflect.Descriptor instead.
func (*RoomLeaveResp) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{3}
}

func (x *RoomLeaveResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoomLeaveResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RoomDestroyedPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomDestroyedPush) Reset() {
	*x = RoomDestroyedPush{}
	mi := &file_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDestroyedPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDestroyedPush) ProtoMessage() {}

func (x *RoomDestroyedPush) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDestroyedPush.ProtoReflect.Descriptor instead.
func (*RoomDestroyedPush) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{4}
}

func (x *RoomDestroyedPush) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type RoomEventPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Event         string                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"` // "joined" | "left"
	PlayerCount   int64                  `protobuf:"varint,4,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventPush) Reset() {
	*x = RoomEventPush{}
	mi := &file_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventPush) ProtoMessage() {}

func (x *RoomEventPush) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventPush.ProtoReflect.Descriptor instead.
func (*RoomEventPush) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{5}
}

func (x *RoomEventPush) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *RoomEventPush) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RoomEventPush) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *RoomEventPush) GetPlayerCount() int64 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

var File_room_proto protoreflect.FileDescriptor

const file_room_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"room.proto\x12\x02pb\"(\n" +
	"\vRoomJoinReq\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"v\n" +
	"\fRoomJoinResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\tR\amatchId\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\")\n" +
	"\fRoomLeaveReq\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"?\n" +
	"\rRoomLeaveResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\".\n" +
	"\x11RoomDestroyedPush\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"\x80\x01\n" +
	"\rRoomEventPush\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05event\x12!\n" +
	"\fplayer_count\x18\x04 \x01(\x03R\vplayerCountB\x15Z\x13cardwar/protocol/pbb\x06proto3"

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData []byte
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)))
	})
	return file_room_proto_rawDescData
}

var file_room_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_room_proto_goTypes = []any{
	(*RoomJoinReq)(nil),       // 0: pb.RoomJoinReq
	(*RoomJoinResp)(nil),      // 1: pb.RoomJoinResp
	(*RoomLeaveReq)(nil),      // 2: pb.RoomLeaveReq
	(*RoomLeaveResp)(nil),     // 3: pb.RoomLeaveResp
	(*RoomDestroyedPush)(nil), // 4: pb.RoomDestroyedPush
	(*RoomEventPush)(nil),     // 5: pb.RoomEventPush
}
var file_room_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		MessageInfos:      file_room_proto_msgTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
